### ISSUE TITLE
Open in browser does not work on Linux

### ISSUE THREAD

**Issue by gmmeyer** [atom-archive/feedback#40]
I first noticed this when I attempted to do the one minute survey. I know that it used to work in Atom, but am not certain when it stopped working. The behavior I see now, however, is much worse and is new.

I am using Ubuntu 14.10. My WM is Awesome. I do have a default browser set.

When I clicked on the button to take the 1 minute survey--the button in the modal, not the one on the bottom of the screen--it froze the text editor. I had to kill it. It did not, in fact, freeze everything. I could still use the developer tools, which is good but I don't really know where to even start looking in that for the root cause of the issue.

This is repeatable. And, it does happen with every browser based link (e.g. package links).

**Comment by benogle** [comment]
:( Wonder if it's related to the Chrome 41 upgrade in 189. I'll try this on ubuntu.

Props to finding the correct repo to submit the issue on.

**Comment by goffreder** [comment]
Same problem here. I have Atom 0.189.0, Chromium 41.0.2272.76 as my default browser. When I click on the button (or in any browser-opening link/button INSIDE Atom), I can see in the process list that it spawn a process with this command:
`chromium-browser --enable-pinch https://atom.io/survey/survey-2015-1/3e829a8ed347db9ce09929c065d782a76d18950a`
but nothing else happens (either with Chromium already open or not).
All the links in the Help menu on the top bar of Ubuntu that should open a browser page work properly (like View Terms of Use).

If I set Firefox as default browser it still doesn't work, but if I remove Chromium (thus leaving Firefox as the only installed browser), it works as expected. Hope it's of any help.

**Comment by gmmeyer** [comment]
Oh, I'm actually not on Chromium, I'm on Chrome 41.0.2272.118.

@goffreder's command works for me. Chrome opens the tab, though I only get a Rails Application Error message from the other end.

So, I don't think it's a browser issue, I think it's probably an Atom issue. And, also, I don't get this behavior from any other application when opening something in my browser, even other Node based applications. 

So, I don't think that's it. (Though it could well be for @goffreder).

**Comment by paulcbetts** [comment]
We've seen this on Chrome 40 too, Linux sucks (*)


* _And by sucks I mean, "It is frustrating to deal with distro-specific differences in software that isn't maintained in every distro's repo"_

**Comment by gmmeyer** [comment]
Which slack for linux app? There's not one available from Slack, so you could be talking about a few different ones.

**Comment by kevinsawicki** [comment]
I've opened up an Atom Shell issue for this https://github.com/atom/atom-shell/issues/1348

**Comment by paulcbetts** [comment]
@gmmeyer The one is currently on my laptop and nobody else's :)

**Comment by xrysanthos** [comment]
The following post did the trick for me:https://askubuntu.com/questions/540939/xdg-open-only-opens-a-new-tab-in-a-new-chromium-window-despite-passing-it-a-url/540940#540940

To see if you have an issue, open a terminal and enter

> xdg-open http://github.com

If you have a problem, you should see a new tab opening but without a URL.

To fix, edit the following files and find the following statement:

> Exec=/usr/bin/google-chrome-stable ....

If it doesn't have a %U flag appended in the URL, just add it by hand, e.g.

> Exec=/usr/bin/google-chrome-stable %U ...

File locations:
- nano  ~/.local/share/applications/google-chrome.desktop
- sudo nano /usr/share/app-install/desktop/chromium-browser:chromium-browser.desktop

Try running the command and now it should work!

**Comment by edelans** [comment]
many thanks @chefArchitect : I have been banging my head the whole day about this issue...

**Comment by Meorne** [comment]
@spilio many thanks ! that work for me !

**Comment by lee-dohm** [comment]
This package is no longer maintained. We do not have and don't intend to build a replacement. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks for your help and support!
